# Generated by Django 6.1.1 on 2026-09-28 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='اسم الاسكربت')),
                ('image', models.ImageField(upload_to='scripts/', verbose_name='صورة الاسكربت')),
                ('description', models.TextField(verbose_name='تفاصيل الاسكربت')),
                ('price', models.CharField(max_length=100, verbose_name='أسعار الاشتراك')),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='اسم الموقع')),
                ('image', models.ImageField(upload_to='websites/', verbose_name='صورة الموقع')),
                ('description', models.TextField(verbose_name='تفاصيل الموقع')),
                ('preview_link', models.URLField(blank=True, null=True, verbose_name='رابط معاينة الموقع')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_type', models.CharField(choices=[('ويب سايت كامل', 'ويب سايت كامل'), ('لاندنج بيدج', 'لاندنج بيدج')], max_length=50, verbose_name='نوع الموقع')),
                ('requested_pages', models.TextField(blank=True, null=True, verbose_name='الصفحات المطلوبة (لو ويب سايت كامل)')),
                ('contact_info', models.CharField(max_length=255, verbose_name='رقم الموبايل أو لينك فيسبوك')),
                ('status', models.CharField(choices=[('جديد', 'طلب جديد'), ('جاري التواصل', 'جاري التواصل'), ('تم التسليم', 'تم التسليم')], default='جديد', max_length=50, verbose_name='حالة الطلب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
            ],
        ),
        migrations.CreateModel(
            name='ScriptOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_info', models.CharField(max_length=255, verbose_name='رقم الموبايل أو لينك فيسبوك')),
                ('status', models.CharField(choices=[('جديد', 'طلب جديد'), ('جاري التواصل', 'جاري التواصل'), ('تم التسليم', 'تم التسليم')], default='جديد', max_length=50, verbose_name='حالة الطلب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.script', verbose_name='الاسكربت المطلوب')),
            ],
        ),
    ]
