# Generated by Django 6.0.2 on 2026-09-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='github_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='رابط جيت هاب'),
        ),
        migrations.AddField(
            model_name='script',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='هل السكريبت مجاني؟'),
        ),
    ]
